server:
  port: ${PORTS:31001}
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: testlocalhost
  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id:  ${spring.application.name}:${server.port} #指定实例id